
CREATE TABLE IF NOT EXISTS "AB_CORE"."PROFESSIONAL_TYPE"
(
  ID serial NOT NULL PRIMARY KEY,
  P_TYPE CHARACTER VARYING(30),
  DESCRIPTION CHARACTER VARYING(255)
);

CREATE TABLE IF NOT EXISTS "AB_CORE"."PROFESSIONAL"
(
	ID Serial NOT NULL PRIMARY KEY,
	TYPE_ID integer references "AB_CORE"."PROFESSIONAL_TYPE"(ID),
	FIRST_NAME CHARACTER VARYING(30)
);